### ISSUE TITLE
Official Databricks Provider

### ISSUE THREAD

**Issue by stack72** [ingenii-solutions/pulumi-databricks#3]
Hi folks

I have been working to produce an official databricks provider in the Pulumi org and we have tried to publish that provider to PyPi and noticed that you have a package already there https://pypi.org/project/pulumi-databricks/

Would you be interested in donating that name to the official Pulumi provider so that we can start publishing to PyPi from the official repo?

Paul

**Comment by markodjukic** [comment]
This has been handed over to Pulumi.
